//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client_weBsite.SqlService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SqlService.ISqlService")]
    public interface ISqlService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/Get_Data", ReplyAction="http://tempuri.org/ISqlService/Get_DataResponse")]
        System.Data.DataSet Get_Data(string dbname, int rollno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISqlService/Get_Data", ReplyAction="http://tempuri.org/ISqlService/Get_DataResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_DataAsync(string dbname, int rollno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISqlServiceChannel : client_weBsite.SqlService.ISqlService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SqlServiceClient : System.ServiceModel.ClientBase<client_weBsite.SqlService.ISqlService>, client_weBsite.SqlService.ISqlService {
        
        public SqlServiceClient() {
        }
        
        public SqlServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SqlServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_Data(string dbname, int rollno) {
            return base.Channel.Get_Data(dbname, rollno);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_DataAsync(string dbname, int rollno) {
            return base.Channel.Get_DataAsync(dbname, rollno);
        }
    }
}
